package com.alejandromejia.hellobuildtest.utils

const val DB_NAME = "HelloBuildDatabase"
const val BASE_URL = "https://jsonplaceholder.typicode.com/"
const val NO_USERS_FOUND = "No users found"
const val RECENT_SEARCH = "Recent Search"
const val NO_FAVORITES = "You don't have any favorite users yet"
const val SORTED_BY = "Sorted by:"
const val EMPTY_STRING = ""
const val OF = "of"
const val USER = "user"
const val USERS = "Users"
const val FAVORITES = "Favorites"
const val CANCEL = "Cancel"
const val SEARCH = "Search by name"
const val GET_USERS = "/users"
const val NAME = "name"
const val EMAIL = "email"
const val PHONE = "phone"
const val SORT_NAME = "Sort by Name"
const val SORT_EMAIL = "Sort by Email"
const val SORT_PHONE = "Sort by Phone"
const val USER_FILTER = "User Filter"
const val PROGRESS_TEXT = "Loading..."
const val UNAUTHORIZED = "Unauthorized"